---
title: "Final Project Stats"
author: "Ahlam Abuawad, Lizzy Gibson & Yanelli Nunez"
date: "November 14, 2017"
output: 
  html_document:
    toc: TRUE
    toc_float: TRUE
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(janitor)
library(rvest)
library(httr)
library(stringr)
library(forcats)

eda_data <- read_csv("./eda_data.csv")
```

## Lead and Poverty

```{r poverty}
summary(eda_data$poverty)
summary(eda_data$lead_percent)
hist(eda_data$lead_percent)


eda_data %>% 
  ggplot(aes(y = lead_percent, x = poverty)) + geom_point() + geom_smooth() +
  labs(x = "Percent of students in poverty", y = "Proportion of pipes with lead > 15 ppb",
       title = "Poverty status and lead exposure")

cor.test(eda_data$lead_percent, eda_data$poverty, method = "spearman", use = "complete.obs")
```

## Lead and Minority Status

```{r minority}
table(eda_data$minority)
tapply(eda_data$lead_percent, eda_data$minority, mean, na.rm = TRUE)

table(eda_data$race)
tapply(eda_data$lead_percent, eda_data$race, mean, na.rm = TRUE)

wilcox.test(lead_percent ~ minority, data = eda_data)
#nonparametric TTEST

kruskal.test(lead_percent ~ as.factor(race), data = eda_data)
#non-parametric ANOVA
```

## Lead and Standardized Test Scores

```{r test}
summary(eda_data$mean_scale_score)
hist(eda_data$mean_scale_score)

eda_data %>% 
  ggplot(aes(y = mean_scale_score, x = lead_percent)) + geom_point() + geom_smooth() +
  labs(y = "Standardized test math scores", x = "Proportion of pipes with lead > 15 ppb",
       title = "Lead exposure and student math scores")

cor.test(eda_data$lead_percent, eda_data$mean_scale_score, method = "spearman", use = "complete.obs")
```

### Race and Standardized Test Scores

```{r minority_test}
table(eda_data$minority)
tapply(eda_data$mean_scale_score, eda_data$minority, mean, na.rm = TRUE)
hist(eda_data$mean_scale_score)

table(eda_data$race)
tapply(eda_data$mean_scale_score, eda_data$race, mean, na.rm = TRUE)

t.test(mean_scale_score ~ minority, data = eda_data)

summary(aov(mean_scale_score ~ as.factor(race), data = eda_data))
```

### Poverty and Standardized Test Scores

```{r poverty_test}
summary(eda_data$poverty)
summary(eda_data$mean_scale_score)

eda_data %>% 
  ggplot(aes(y = mean_scale_score, x = poverty)) + geom_point() + geom_smooth(method = "lm") +
  labs(x = "Percent of students in poverty", y = "Standardized test math scores",
       title = "Poverty status and student math scores")

cor.test(eda_data$mean_scale_score, eda_data$poverty, use = "complete.obs")

eda_data %>% 
  lm(mean_scale_score ~ poverty, data = .) %>% 
  broom::tidy() %>% 
  select(-std.error, -statistic) %>% 
  knitr::kable()
```

